### PR TITLE
Frontend improvements.

### LINKED ISSUE #67: Frontend improvements
- [ ] favicon, app name

- [ ] platform name

### PR DESCRIPTION
**Pull request by iberdinsky-skilld**
Closes #67 

vars.yaml in root directory

```
plasmactl_web_ui_platform_name: 'Custom Platform Name'
plasmactl_web_ui_platform_favicon:
  '<svg width="300" height="130" xmlns="http://www.w3.org/2000/svg">
    <rect width="200" height="100" x="10" y="10" rx="20" ry="20" fill="blue" />
  </svg>'
plasmactl_web_ui_platform_logo:
  '<svg width="300" height="130" xmlns="http://www.w3.org/2000/svg">
    <rect width="200" height="100" x="10" y="10" rx="20" ry="20" fill="blue" />
  </svg>'
  ```

### CODE REVIEW

**Comment by davidferlay** [comment]
image

**Comment by iberdinsky-skilld** [comment]
Also 

[Image from Gyazo](https://gyazo.com/3afc093c1a20211825612da5d01820bb)

**Comment by davidferlay** [comment]
- 1/5 solved in incognito window 
image

- Issue in relative/aboslute binary path:
   - `./plasmactlui web --foreground --swagger-ui` > data ok
   - `plasmactlui web --foreground --swagger-ui` > data empty
image

**Comment by iberdinsky-skilld** [comment]
Moved backend issue `relative/aboslute binary path` to own ticket

**Pull request merged**
