### PR TITLE
Adding examples of actions, including RJSF examples for different set of types

### PR DESCRIPTION
**Pull request by koskinpark**
ui schemas are placed, but not working
I actually have copied all actions from https://github.com/launchrctl/launchr/tree/main/example
And also added several RJSF actions with various set of types with some long test docker command execution

### CODE REVIEW

**Comment by iberdinsky-skilld** [comment]
Probably we don't need DockerFiles and main.sh here. 

@davidferlay 
@lexbritvin 

Could you please check?

**Comment by iberdinsky-skilld** [comment]
Other looks good to me.

**Comment by davidferlay** [comment]
> Probably we don't need DockerFiles and main.sh here.

Depends if you need actions to work successfully or not

If not, only `actions/*/action.yaml` is needed

**Comment by iberdinsky-skilld** [comment]
Let's merge then. we can manage it later.

**Pull request merged**
