### PR TITLE
Kbar implemented

### PR DESCRIPTION
**Pull request by iberdinsky-skilld**
https://refine.dev/docs/packages/command-palette/
https://kbar.vercel.app/

[Image from Gyazo](https://gyazo.com/da8968359f4737e853e57e1c5131b088)

### CODE REVIEW

**Comment by davidferlay** [comment]
Works but :
- would be great that it also changes selection in main windows + left sidebar 
image
- would be great to make it available on all pages of webapp: for now it's only avaiable on /actions page

**Comment by iberdinsky-skilld** [comment]
I've created simplification issue

https://github.com/launchrctl/web/issues/86

should be one context for selected actions. 
https://gyazo.com/64d00f6499e06ceb7c7fd51cbb895fe2

**Comment by iberdinsky-skilld** [comment]
I've added context refactoring. please review.

**Comment by davidferlay** [comment]
- [ ] would be great to make it available on all pages of webapp: for now it's only avaiable on /actions page

**Comment by iberdinsky-skilld** [comment]
At the moment we can move from /actions and /actions/id page to /flow with highlighted form 
basic feature works.
i suggest to merge it and resolve the rest in:

https://github.com/launchrctl/web/issues/86


we still have 2 contexts of active action.

**Pull request merged**
